flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: cff794399744a4038c0f2b2dfbc4c43593d2bcbd
- location:
    git: https://github.com/aisamanra/s-cargot.git
    commit: 1628a7c2913fc5e72ab6ea9a813762bf86d47d49
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: 7f8147e0fbfe210df9e6c83f4c0d48c3de4ed9f7
extra-deps:
  - cereal-plus-0.4.0
resolver: lts-2.21
