flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 348b07492a87218a428b6753e05f2f1ded0e0106
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: 7f8147e0fbfe210df9e6c83f4c0d48c3de4ed9f7
extra-deps:
  - cereal-plus-0.4.0
  - s-cargot-0.1.0.0
resolver: lts-2.21
