flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 18d603078d327bc08e790d7c4ae3e721760058b5
- location:
    git: https://github.com/aisamanra/s-cargot.git
    commit: 1628a7c2913fc5e72ab6ea9a813762bf86d47d49
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: 7f8147e0fbfe210df9e6c83f4c0d48c3de4ed9f7
extra-deps:
  - hastache-0.6.0
  - cereal-plus-0.4.0
resolver: lts-2.21
