flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 7d44a8e2c027a93d7937b29aa9915a082919f6c5
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: b2125cf19e64411c08b10a26bd8dffa17e11ec0e
extra-deps:
  - cereal-plus-0.4.2
  - s-cargot-0.1.0.0
  - gitrev-1.2.0
resolver: lts-7.18
